#!/usr/bin/python3
data=[]
def iterator(f):
        for line in f.readlines():
                data.append(line.split(":")[0])
        data.sort()
        for item in data:
                print("-" + item)

with open("/etc/passwd","r") as fp:
        print("\n* USERS *")
        iterator(fp)
